INSERT INTO student (lastName, name, fatherName, phone, telegram, mail, git)  
VALUES 
('Иванов', 'Пётр', 'Николаевич', '+79123456789', '@ivanov_pn', 'peter.ivanov@example.com', 'https://github.com/IvanovPN'), 
('Сидорова', 'Анна', 'Михайловна', '+79234567890', '@sidorova_am', 'anna.sidorova@example.com', 'https://github.com/SidorovaAM'), 
('Петрова', 'Елена', 'Сергеевна', '+794567111111', '@petrova_es', 'elena.petrova@example.com', 'https://github.com/PetrovaES'), 
('Кислица', 'Данил', 'Александрович', '+79833777777', '@danya_kis', 'streleckiy.io@mail.ru', 'https://github.com/efftea'),
('Ivanov', 'Ivan', 'Ivanovich', '+79991234567', NULL, 'ivanii@mail.ru', 'https://github.com/ivanii'),
('Petrov', 'Petr', 'Petrovich', NULL, '@petrpp', NULL, 'https://github.com/PPPetr'),
('Semenov', 'Semen', 'Semenovich', NULL, NULL, 'semenses@mail.ru', 'https://github.com/SSemenS'),
('Smirnov', 'Alexander', 'Smirnovich', '+79997654321', '@asmirnov', 'alexsmirnov@mail.ru', 'https://github.com/asmirnov'),
('Kuznetsov', 'Igor', 'Igorevich', '+79999112233', NULL, 'igork@mail.com', 'https://github.com/IgorK'),
('Popova', 'Elena', 'Nikolaevna', NULL, '@epopova', NULL, 'https://github.com/epopova'),
('Volkova', 'Anna', 'Sergeevna', '+79998887766', NULL, 'annakova@mail.com', 'https://github.com/volkova'),
('Lebedev', 'Dmitry', 'Andreevich', '+79993334455', NULL, NULL, 'https://github.com/dlebedev'),
('Kovalev', 'Mikhail', 'Olegovich', NULL, '@mkovalev', 'mishalev@mail.ru', 'https://github.com/mkovalev'),
('Makarova', 'Olga', 'Pavlovna', '+79994561234', NULL, 'olgamak@mail.ru', 'https://github.com/olgamakarova'),
('Zaytsev', 'Yuri', 'Nikolaevich', NULL, '@yzaytsev', 'zaytsev@mail.com', 'https://github.com/yuriz'),
('Novikova', 'Irina', 'Igorevna', '+79996785943', NULL, NULL, 'https://github.com/irinanova'),
('Morozov', 'Pavel', 'Petrovich', NULL, '@pmorozov', 'morozovp@mail.com', 'https://github.com/pavelmorozov'),
('Vasiliev', 'Alexey', 'Vladimirovich', '+79994567382', NULL, NULL, 'https://github.com/avvasiliev'),
('Karpov', 'Nikita', 'Ivanovich', '+79995123456', '@karpovnikita', 'nikkarpov@mail.ru', 'https://github.com/nkarpov');