INSERT INTO student (surname, name, patronymic, tg, git, email, phone)
VALUES ('Ivanov', 'Ivan', 'Ivanovich', NULL, 'github.com/ivanii', NULL, '89991234567'),
('Petrov', 'Petr', 'Petrovich', '@petrpp', 'github.com/PPPetr', NULL, NULL),
('Semenov', 'Semen', 'Semenovich', NULL, 'github.com/SSemenS', 'semenses@mail.ru', NULL),
('Smirnov', 'Alexander', 'Smirnovich', '@asmirnov', 'github.com/asmirnov', 'alexsmirnov@mail.ru', '89997654321'),
('Kuznetsov', 'Igor', 'Igorevich', NULL, 'github.com/IgorK', 'igork@mail.com', '89999112233'),
('Popova', 'Elena', 'Nikolaevna', '@epopova', 'github.com/epopova', NULL, NULL),
('Volkova', 'Anna', 'Sergeevna', NULL, 'github.com/volkova', 'annakova@mail.com', '89998887766'),
('Lebedev', 'Dmitry', 'Andreevich', NULL, 'github.com/dlebedev', NULL, '89993334455'),
('Kovalev', 'Mikhail', 'Olegovich', '@mkovalev', 'github.com/mkovalev', 'mishalev@mail.ru', NULL),
('Makarova', 'Olga', 'Pavlovna', NULL, 'github.com/olgamakarova', 'olgamak@mail.ru', '89994561234'),
('Zaytsev', 'Yuri', 'Nikolaevich', '@yzaytsev', 'github.com/yuriz', 'zaytsev@mail.com', NULL),
('Novikova', 'Irina', 'Igorevna', NULL, 'github.com/irinanova', NULL, '89996785943'),
('Morozov', 'Pavel', 'Petrovich', '@pmorozov', 'github.com/pavelmorozov', 'morozovp@mail.com', NULL),
('Vasiliev', 'Alexey', 'Vladimirovich', NULL, 'github.com/avvasiliev', NULL, '89994567382'),
('Karpov', 'Nikita', 'Ivanovich', '@karpovnikita', 'github.com/nkarpov', 'nikkarpov@mail.ru', '89995123456');